### PR TITLE
Fix GoReleaser

### PR DESCRIPTION
**Pull request by arbourd**
Use the action to install the binary and run goreleaser inside of a nix
shell.

### CODE REVIEW

**Comment by angelini** [comment]
Does this happen to bump the Go version because the default is higher in Nix's package manager?

**Comment by arbourd** [comment]
Nah, I think it's because the nix environment isn't getting sourced and therefor not on the path. By switching it to `nix develop -c` we should be setting up the path properly. Will need to run it to be 100%.

What's the deal with the protobufs tho? Those probably need to be built yes?

**Comment by angelini** [comment]
> What's the deal with the protobufs tho? Those probably need to be built yes?

Yeah we need to run this step before the build is executed:

https://github.com/gadget-inc/fsdiff/blob/main/Makefile#L5-L6

```make
pkg/pb/%.pb.go: pkg/pb/%.proto
	protoc --experimental_allow_proto3_optional --go_out=. --go_opt=paths=source_relative $^
```

**Comment by arbourd** [comment]
Tested locally this time:

```console
$ nix develop -c goreleaser release --skip-publish --skip-validate --rm-dist
   • releasing...
   • loading config file       file=.goreleaser.yml
   • loading environment variables
   • getting and validating git state
      • building...               commit=45eae448d5e5e73583f695b8cdbba496a981dbca latest tag=v0.3.3
      • pipe skipped              error=validation is disabled
   • parsing tag
   • running before hooks
      • running                   hook=go mod download
      • running                   hook=make pkg/pb/diff.pb.go pkg/pb/summary.pb.go
   • setting defaults
      • snapshotting
      • scm releases
      • project name
      • loading go mod information
      • building binaries
      • universal binaries
      • creating source archive
      • archives
      • linux packages
      • snapcraft packages
      • calculating checksums
      • signing artifacts
      • signing docker images
      • docker images
      • docker manifests
      • artifactory
      • blobs
      • homebrew tap formula
      • krew plugin manifest
      • gofish fish food cookbook
      • scoop manifests
      • discord
      • reddit
      • slack
      • teams
      • twitter
      • smtp
      • mattermost
      • milestones
      • linkedin
      • telegram
   • checking distribution directory
   • loading go mod information
   • writing effective config file
      • writing                   config=dist/config.yaml
   • building binaries
      • building                  binary=/Users/dylan/src/github.com/gadget-inc/fsdiff/dist/fsdiff_darwin_arm64/fsdiff
      • building                  binary=/Users/dylan/src/github.com/gadget-inc/fsdiff/dist/fsdiff_linux_amd64/fsdiff
      • building                  binary=/Users/dylan/src/github.com/gadget-inc/fsdiff/dist/fsdiff_linux_arm64/fsdiff
      • building                  binary=/Users/dylan/src/github.com/gadget-inc/fsdiff/dist/fsdiff_darwin_amd64/fsdiff
   • archives
      • creating                  archive=dist/fsdiff-v0.3.3-linux-arm64.tar.gz
      • creating                  archive=dist/fsdiff-v0.3.3-darwin-arm64.tar.gz
      • creating                  archive=dist/fsdiff-v0.3.3-darwin-amd64.tar.gz
      • creating                  archive=dist/fsdiff-v0.3.3-linux-amd64.tar.gz
   • calculating checksums
      • checksumming              file=fsdiff-v0.3.3-darwin-amd64.tar.gz
      • checksumming              file=fsdiff-v0.3.3-darwin-arm64.tar.gz
      • checksumming              file=fsdiff-v0.3.3-linux-amd64.tar.gz
      • checksumming              file=fsdiff-v0.3.3-linux-arm64.tar.gz
   • release succeeded after 1.31s
   ```

**Review by angelini — APPROVED** [review]
Awesome!

**Comment by angelini** [comment]
This failed on Github Actions with:

```
   ⨯ release failed after 0.68s error=hook failed: make pkg/pb/diff.pb.go pkg/pb/summary.pb.go: exit status 2; output: protoc --experimental_allow_proto3_optional --go_out=. --go_opt=paths=source_relative pkg/pb/diff.proto
make: protoc: No such file or directory
make: *** [Makefile:6: pkg/pb/diff.pb.go] Error 127
```

Do we need to first run something to install everything in our flake file?

**Comment by arbourd** [comment]
I feel like we're missing `protoc` in general, but not sure how `make build` passes. Guessing but maybe `make` is smart enough that the `pb.go` files exist already in that context and don't need to be generated?

Probably the same thing locally because I don't have protoc on my path either.

**Comment by angelini** [comment]
🤦 

In DateiLager I include the required steps for installing everything: https://github.com/gadget-inc/dateilager/blob/main/Makefile#L24-L26

But I don't have that for `fsdiff`.

And because I forgot to add the `pb.go` files to `.gitignore` it just works...

**Comment by angelini** [comment]
I'll PR up those changes, I'd prefer to always build the generated files to ensure we can't forget that when deploying a new version.

**Comment by arbourd** [comment]
I don't even think we need protoc because we are checking the pb.go into source too. Really, that's just going to cause side effects?

**Pull request merged**
